/**
 * Test fixture initialiser — one-time setup for the e2e test admin.
 *
 * Why this exists
 * ---------------
 * Every authenticated route in this project is gated by mandatory TOTP. To
 * run Playwright UAT specs we need a known TOTP secret so each test run can
 * sign in non-interactively. This script enrols TOTP for the test admin
 * user (created by the project's bootstrap step) by driving Better Auth's
 * HTTP endpoints exactly the way the production app does, and persists the
 * resulting secret to `e2e/.env.fixture`.
 *
 * The fixture file is gitignored. After resetting the database and
 * re-running the bootstrap step, re-run `pnpm test:fixture-init` to re-enrol
 * and rewrite the secret.
 *
 * Idempotency
 * -----------
 * Running this script when TOTP is already enrolled and `e2e/.env.fixture`
 * already contains a matching secret is a no-op. Running it when TOTP is
 * already enrolled but the fixture file is missing is a fatal error: BA
 * stores secrets hashed and there is no way to recover the original. Reset
 * the database and re-bootstrap to recover.
 *
 * Invariants — these come from production-tested BA quirks
 * --------------------------------------------------------
 *   - Every POST that carries a Cookie header MUST also send Origin: APP_URL.
 *     BA's origin-check middleware returns 403 FORBIDDEN otherwise.
 *   - We use raw fetch against the BA HTTP route, not auth.api.* — the
 *     internal API discards Set-Cookie headers from setSessionCookie().
 */
/* eslint-disable no-console */

import fs from 'node:fs'
import path from 'node:path'
import { authenticator } from 'otplib'

interface BootstrapEnv {
  appUrl: string
  email: string
  password: string
}

function readEnv(): BootstrapEnv {
  const appUrl = process.env.APP_URL
  const email = process.env.TEST_ADMIN_EMAIL
  const password = process.env.TEST_ADMIN_PASSWORD
  if (!appUrl) throw new Error('APP_URL is required (set in .env.local).')
  if (!email) throw new Error('TEST_ADMIN_EMAIL is required (set in .env.local).')
  if (!password) throw new Error('TEST_ADMIN_PASSWORD is required (set in .env.local).')
  return { appUrl, email, password }
}

const FIXTURE_PATH = path.resolve(process.cwd(), 'e2e', '.env.fixture')

function readExistingSecret(): string | null {
  try {
    const raw = fs.readFileSync(FIXTURE_PATH, 'utf8')
    const match = raw.match(/^TEST_ADMIN_TOTP_SECRET=(.+)$/m)
    return match ? match[1].trim() : null
  } catch {
    return null
  }
}

function writeSecret(secret: string): void {
  const dir = path.dirname(FIXTURE_PATH)
  fs.mkdirSync(dir, { recursive: true })
  const body =
    '# Generated by `pnpm test:fixture-init`. Gitignored. Do not edit by hand.\n' +
    '# Re-generate after a database reset: bootstrap admin user, then re-run.\n' +
    `TEST_ADMIN_TOTP_SECRET=${secret}\n`
  fs.writeFileSync(FIXTURE_PATH, body, { encoding: 'utf8', mode: 0o600 })
}

function setCookieHeaders(res: Response): string[] {
  const headers = res.headers as Headers & { getSetCookie?: () => string[] }
  if (typeof headers.getSetCookie === 'function') return headers.getSetCookie()
  const single = res.headers.get('set-cookie')
  return single ? [single] : []
}

function cookieHeaderFromSetCookies(setCookies: string[]): string {
  return setCookies
    .map((raw) => raw.split(';', 1)[0]?.trim())
    .filter((s): s is string => Boolean(s))
    .join('; ')
}

interface SignInOutcome {
  setCookies: string[]
  twoFactorChallenge: boolean
  body: unknown
}

async function signIn(env: BootstrapEnv): Promise<SignInOutcome> {
  const res = await fetch(`${env.appUrl}/api/auth/sign-in/email`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Origin': env.appUrl,
      'Accept': 'application/json',
    },
    body: JSON.stringify({ email: env.email, password: env.password }),
    redirect: 'manual',
  })

  if (!res.ok && res.status !== 200) {
    const text = await res.text().catch(() => '')
    throw new Error(`Sign-in failed: HTTP ${res.status}. Response: ${text}`)
  }

  const setCookies = setCookieHeaders(res)
  let body: unknown = null
  try { body = await res.json() } catch { /* empty body OK */ }

  const twoFactorChallenge =
    typeof body === 'object' && body !== null && (body as { twoFactorRedirect?: boolean }).twoFactorRedirect === true

  return { setCookies, twoFactorChallenge, body }
}

async function enableTotp(env: BootstrapEnv, cookieHeader: string): Promise<{ totpURI: string; backupCodes: string[] }> {
  const res = await fetch(`${env.appUrl}/api/auth/two-factor/enable`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Origin': env.appUrl,
      'Accept': 'application/json',
      'Cookie': cookieHeader,
    },
    body: JSON.stringify({ password: env.password }),
    redirect: 'manual',
  })

  if (!res.ok) {
    const text = await res.text().catch(() => '')
    throw new Error(`enableTwoFactor failed: HTTP ${res.status}. Response: ${text}`)
  }

  const body = (await res.json()) as { totpURI?: string; backupCodes?: string[] }
  if (!body.totpURI || !Array.isArray(body.backupCodes)) {
    throw new Error(`enableTwoFactor returned unexpected shape: ${JSON.stringify(body)}`)
  }
  return { totpURI: body.totpURI, backupCodes: body.backupCodes }
}

async function verifyTotp(env: BootstrapEnv, code: string, cookieHeader: string): Promise<void> {
  const res = await fetch(`${env.appUrl}/api/auth/two-factor/verify-totp`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Origin': env.appUrl,
      'Accept': 'application/json',
      'Cookie': cookieHeader,
    },
    body: JSON.stringify({ code }),
    redirect: 'manual',
  })

  if (!res.ok) {
    const text = await res.text().catch(() => '')
    throw new Error(`verifyTOTP failed: HTTP ${res.status}. Response: ${text}`)
  }
}

function parseSecretFromOtpauthUri(totpURI: string): string {
  const url = new URL(totpURI)
  const secret = url.searchParams.get('secret')
  if (!secret) throw new Error(`otpauth URI did not contain a secret: ${totpURI}`)
  return secret
}

async function main(): Promise<void> {
  const env = readEnv()
  console.log(`[fixture-init] APP_URL=${env.appUrl} email=${env.email}`)

  const signin = await signIn(env)

  if (signin.twoFactorChallenge) {
    const existing = readExistingSecret()
    if (existing) {
      console.log('[fixture-init] TOTP already enrolled and e2e/.env.fixture present — nothing to do.')
      return
    }
    throw new Error(
      'TOTP is already enrolled for this user but e2e/.env.fixture is missing.\n' +
      'BA stores secrets hashed; the original cannot be recovered.\n' +
      'Recover by resetting the DB, re-running the bootstrap step, then re-running this script.',
    )
  }

  const cookieHeader = cookieHeaderFromSetCookies(signin.setCookies)
  if (!cookieHeader) {
    throw new Error(
      'Sign-in succeeded but no cookies were returned. ' +
      'Cannot proceed with TOTP enrolment. Check that APP_URL matches the running server.',
    )
  }

  console.log('[fixture-init] Signed in. Enrolling TOTP via Better Auth /two-factor/enable...')
  const { totpURI } = await enableTotp(env, cookieHeader)
  const secret = parseSecretFromOtpauthUri(totpURI)

  authenticator.options = { window: 1 }
  const code = authenticator.generate(secret)
  console.log('[fixture-init] Verifying TOTP code to finalise enrolment...')
  await verifyTotp(env, code, cookieHeader)

  writeSecret(secret)
  console.log(`[fixture-init] Wrote TEST_ADMIN_TOTP_SECRET to ${FIXTURE_PATH}`)
  console.log('[fixture-init] Done. Run `pnpm e2e` to execute the suite.')
}

main().catch((err: unknown) => {
  console.error('[fixture-init] FAILED:', err instanceof Error ? err.message : err)
  process.exit(1)
})
