/**
 * AuthDriver: Better Auth + twoFactor (TOTP) plugin.
 *
 * Drop this file at e2e/auth-driver.ts to use it. Requires `otplib` in
 * devDependencies.
 *
 * Required env (in .env.local):
 *   APP_URL                   - base URL of the running app
 *   TEST_ADMIN_EMAIL          - test user email
 *   TEST_ADMIN_PASSWORD       - test user password
 *
 * Persisted secrets (written to e2e/.env.fixture by initFixture):
 *   TEST_ADMIN_TOTP_SECRET    - the TOTP seed parsed out of BA's otpauth URI
 *
 * Invariants — production-tested workarounds for BA quirks. Removing them
 * causes silent failures that are hard to diagnose:
 *
 *   1. Every cookie-bearing POST sends Origin: APP_URL. BA's origin-check
 *      middleware returns 403 FORBIDDEN otherwise.
 *   2. Calls go to BA HTTP routes, not auth.api.*. The internal API path
 *      discards Set-Cookie headers from setSessionCookie().
 *   3. Cookie values returned to the harness are wire-format — never
 *      decodeURIComponent'd. The harness's storageState forwards them
 *      verbatim, and decoding would double-encode BA's signed cookies.
 */
/* eslint-disable no-console */

import fs from 'node:fs'
import path from 'node:path'
import { authenticator } from 'otplib'
import type { AuthDriver } from './auth-driver.types'

interface BAEnv {
  appUrl: string
  email: string
  password: string
}

function readEnv(): BAEnv {
  const appUrl = process.env.APP_URL
  const email = process.env.TEST_ADMIN_EMAIL
  const password = process.env.TEST_ADMIN_PASSWORD
  if (!appUrl) throw new Error('APP_URL is required (set in .env.local).')
  if (!email) throw new Error('TEST_ADMIN_EMAIL is required (set in .env.local).')
  if (!password) throw new Error('TEST_ADMIN_PASSWORD is required (set in .env.local).')
  return { appUrl, email, password }
}

const FIXTURE_PATH = path.resolve(process.cwd(), 'e2e', '.env.fixture')

function readPersistedSecret(): string | null {
  try {
    const raw = fs.readFileSync(FIXTURE_PATH, 'utf8')
    const match = raw.match(/^TEST_ADMIN_TOTP_SECRET=(.+)$/m)
    return match ? match[1].trim() : null
  } catch {
    return null
  }
}

function writeSecret(secret: string): void {
  fs.mkdirSync(path.dirname(FIXTURE_PATH), { recursive: true })
  const body =
    '# Generated by `pnpm test:fixture-init`. Gitignored. Do not edit by hand.\n' +
    '# Re-generate after a database reset: bootstrap the test admin, then re-run.\n' +
    `TEST_ADMIN_TOTP_SECRET=${secret}\n`
  fs.writeFileSync(FIXTURE_PATH, body, { encoding: 'utf8', mode: 0o600 })
}

function setCookieHeaders(res: Response): string[] {
  const headers = res.headers as Headers & { getSetCookie?: () => string[] }
  if (typeof headers.getSetCookie === 'function') return headers.getSetCookie()
  const single = res.headers.get('set-cookie')
  return single ? [single] : []
}

function cookieHeaderFromSetCookies(setCookies: string[]): string {
  return setCookies
    .map((raw) => raw.split(';', 1)[0]?.trim())
    .filter((s): s is string => Boolean(s))
    .join('; ')
}

interface SignInOutcome {
  setCookies: string[]
  twoFactorChallenge: boolean
}

async function signIn(env: BAEnv): Promise<SignInOutcome> {
  const res = await fetch(`${env.appUrl}/api/auth/sign-in/email`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Origin': env.appUrl,
      'Accept': 'application/json',
    },
    body: JSON.stringify({ email: env.email, password: env.password }),
    redirect: 'manual',
  })

  if (!res.ok) {
    const text = await res.text().catch(() => '')
    throw new Error(`BA sign-in/email failed: HTTP ${res.status}. Response: ${text}`)
  }

  let body: unknown = null
  try { body = await res.json() } catch { /* empty body acceptable */ }

  const twoFactorChallenge =
    typeof body === 'object' && body !== null && (body as { twoFactorRedirect?: boolean }).twoFactorRedirect === true

  return { setCookies: setCookieHeaders(res), twoFactorChallenge }
}

async function enableTotp(env: BAEnv, cookieHeader: string): Promise<{ totpURI: string }> {
  const res = await fetch(`${env.appUrl}/api/auth/two-factor/enable`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Origin': env.appUrl,
      'Accept': 'application/json',
      'Cookie': cookieHeader,
    },
    body: JSON.stringify({ password: env.password }),
    redirect: 'manual',
  })

  if (!res.ok) {
    const text = await res.text().catch(() => '')
    throw new Error(`BA two-factor/enable failed: HTTP ${res.status}. Response: ${text}`)
  }

  const body = (await res.json()) as { totpURI?: string }
  if (!body.totpURI) throw new Error(`two-factor/enable returned no totpURI: ${JSON.stringify(body)}`)
  return { totpURI: body.totpURI }
}

async function verifyTotp(env: BAEnv, code: string, cookieHeader: string): Promise<string[]> {
  const res = await fetch(`${env.appUrl}/api/auth/two-factor/verify-totp`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Origin': env.appUrl,
      'Accept': 'application/json',
      'Cookie': cookieHeader,
    },
    body: JSON.stringify({ code }),
    redirect: 'manual',
  })

  if (!res.ok) {
    const text = await res.text().catch(() => '')
    throw new Error(`BA two-factor/verify-totp failed: HTTP ${res.status}. Response: ${text}`)
  }
  return setCookieHeaders(res)
}

function parseSecretFromOtpauthUri(totpURI: string): string {
  const url = new URL(totpURI)
  const secret = url.searchParams.get('secret')
  if (!secret) throw new Error(`otpauth URI did not contain a secret: ${totpURI}`)
  return secret
}

const driver: AuthDriver = {
  async initFixture(): Promise<void> {
    const env = readEnv()
    console.log(`[ba-totp] APP_URL=${env.appUrl} email=${env.email}`)

    const signin = await signIn(env)

    if (signin.twoFactorChallenge) {
      const existing = readPersistedSecret()
      if (existing) {
        console.log('[ba-totp] TOTP already enrolled and e2e/.env.fixture present — nothing to do.')
        return
      }
      throw new Error(
        'TOTP is already enrolled for this user but e2e/.env.fixture is missing.\n' +
        'BA stores secrets hashed; the original cannot be recovered.\n' +
        'Recover by resetting the DB, re-running the bootstrap step, then re-running this script.',
      )
    }

    const cookieHeader = cookieHeaderFromSetCookies(signin.setCookies)
    if (!cookieHeader) {
      throw new Error('Sign-in succeeded but no cookies were returned. Check that APP_URL matches the running server.')
    }

    console.log('[ba-totp] Signed in. Enrolling TOTP via BA /two-factor/enable...')
    const { totpURI } = await enableTotp(env, cookieHeader)
    const secret = parseSecretFromOtpauthUri(totpURI)

    authenticator.options = { window: 1 }
    const code = authenticator.generate(secret)
    console.log('[ba-totp] Verifying TOTP code to finalise enrolment...')
    await verifyTotp(env, code, cookieHeader)

    writeSecret(secret)
    console.log(`[ba-totp] Wrote TEST_ADMIN_TOTP_SECRET to ${FIXTURE_PATH}`)
  },

  async authenticate(): Promise<{ setCookies: string[]; host: string }> {
    const env = readEnv()
    const secret = process.env.TEST_ADMIN_TOTP_SECRET
    if (!secret) {
      throw new Error(
        'TEST_ADMIN_TOTP_SECRET is missing.\n' +
        'Run `pnpm test:fixture-init` once after bootstrapping the test admin.',
      )
    }

    const signin = await signIn(env)
    if (!signin.twoFactorChallenge) {
      throw new Error(
        'Sign-in did not return a TOTP challenge — the test user has no TOTP enrolled.\n' +
        'Run `pnpm test:fixture-init`.',
      )
    }
    const signinCookieHeader = cookieHeaderFromSetCookies(signin.setCookies)

    authenticator.options = { window: 1 }
    const code = authenticator.generate(secret)
    const verifyCookies = await verifyTotp(env, code, signinCookieHeader)

    return {
      setCookies: [...signin.setCookies, ...verifyCookies],
      host: new URL(env.appUrl).hostname,
    }
  },
}

export default driver
